### ISSUE TITLE
dont run with nix run 

### ISSUE THREAD

**Issue by ZanovelloAlberto** [vilhelmbergsoe/asciicam#1]
![lastscreen](https://github.com/vilhelmbergsoe/asciicam/assets/46749229/059a3380-d97b-47c1-abb6-39d82d4bb45e)
e insomma

**Comment by vilhelmbergsoe** [comment]
Hi Alberto, this seems as though v4l (video 4 linux) didn't find your webcam on the default device 0.
Right now, this is just a very basic little side project so I haven't put in the time to have it look different places for your webcam.
That's also the reason for the bad error message.
If you can, I'd like to see what device your webcam is under? Usually it is located at /dev/video0 for most machines I've used.
I can add a better error message for this specific issue, but I think the automatic webcam device finding is a bit more involved so that's not something I'm going to take up currently.
You can always send a PR if you solve this problem, and I'd be happy to merge it!

**Comment by ZanovelloAlberto** [comment]
yes the camera was not pulgged

**Comment by vilhelmbergsoe** [comment]
Okay, sounds good! I have fixed the error message and now it says:
![image](https://github.com/vilhelmbergsoe/asciicam/assets/16240002/cfcad19a-e69f-4216-97e3-ae9130712ea5)
Thanks for opening the issue Alberto!
